version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: tron_app_psql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: tron_app
    ports:
      - "8001:8000"
    depends_on:
      - postgres

volumes:
  postgres-data: