"""empty message

Revision ID: 396f67580335
Revises:
Create Date: 2025-04-15 18:24:49.288148

"""
from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "396f67580335"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("wallet_queries",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("tron_address", sa.String(), nullable=False),
    sa.Column("query_time", sa.DateTime(timezone=True), nullable=False),
    sa.Column("status", sa.Enum("SUCCESS", "FAILURE", name="querystatus"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallet_queries")
    # ### end Alembic commands ###
